// Language mapping used across all services
export const LANGUAGE_MAP = {
  'tamil': 'Tamil',
  'telugu': 'Telugu',
  'kannada': 'Kannada',
  'hindi': 'Hindi',
  'english': 'English'
};

// Educational YouTube channels (moved from youtube.js)
export const EDUCATIONAL_CHANNELS = [
  "Veritasium", "Vsauce", "Kurzgesagt – In a Nutshell", "MinutePhysics", 
  "SmarterEveryDay", "Physics Girl", "Mark Rober", "Numberphile",
  "3Blue1Brown", "Computerphile", "Tom Scott", "Real Engineering",
  "Practical Engineering", "ElectroBOOM", "The Action Lab", "NileRed",
  "Cody'sLab", "Applied Science", "Steve Mould", "Sixty Symbols",
  "Bozeman Science", "Amoeba Sisters", "Science Simplified",
  "It's AumSum Time", "Peekaboo Kidz", "Happy Learning English",
  "Free School", "Homeschool Pop", "Smile and Learn - English",
  "The Science Classroom", "Moomoomath and Science", "Science Max",
  "Khan Academy", "Mathologer", "Eddie Woo", "blackpenredpen", 
  "The Organic Chemistry Tutor", "Professor Leonard", "PatrickJMT", 
  "Math Antics", "Mashup Math", "Tecmath", "MathAntics", "Math Meeting",
  "freeCodeCamp.org", "CS Dojo", "Traversy Media", "The Net Ninja",
  "Programming with Mosh", "Fireship", "Web Dev Simplified",
  "Academind", "The Coding Train", "Corey Schafer", "Tech With Tim",
  "CrashCourse", "OverSimplified", "History Matters", "The Great War",
  "Kings and Generals", "Epic History TV", "History Buffs",
  "Biographics", "Geographics", "Timeline - World History Documentaries",
  "Osmosis", "Armando Hasudungan", "Ninja Nerd", "Professor Dave Explains", 
  "Medicosis Perfectionalis", "Biology Online",
  "Plant Abundance", "Crime Pays But Botany Doesn't", "Botany One", 
  "The Botanical Explorer", "Plant Science", "In Defense of Plants", 
  "Botany with Dr. Caruso", "Agricultural Sciences", "Plant Cell Biology",
  "Tyler DeWitt", "Melissa Maribel", "The Chemistry Solution", "Conquer Chemistry",
  "Physics Wallah", "Michel van Biezen", "Doc Schuster", 
  "For the Love of Physics", "Physics Online", "The Science Asylum", 
  "Domain of Science", "Lesics", "Engineering Explained", "Branch Education", 
  "The Efficient Engineer", "Economics Explained", "The Plain Bagel", 
  "Two Cents", "ColdFusion", "Wendover Productions", "PolyMatter",
  "Easy Languages", "Learn English with EnglishClass101.com",
  "SpanishDict", "FrenchPod101", "JapanesePod101",
  "The School of Life", "Wireless Philosophy", "Academy of Ideas", 
  "Philosophy Tube", "TED", "TED-Ed", "TEDx Talks", "National Geographic", 
  "Smithsonian Channel", "BBC Earth", "Discovery", "SciShow", "Vox", 
  "AsapSCIENCE", "CGP Grey", "It's Okay To Be Smart", "Seeker",
  "Simple Learning Pro", "Learning Junction", "Kids Academy",
  "Crash Course Kids", "SciShow Kids", "National Geographic Kids",
  "Simple History", "Easy Science", "Learn Bright",
  "Our Changing Climate", "ClimateAdam", "Hot Mess",
  "Conservation International", "World Wildlife Fund",
  "The Nature Conservancy", "Ecology and Environment",
  "IRIS Earthquake Science", "Geology Hub", "GEO GIRL",
  "Nick Zentner", "Earth Science", "Geoscience Videos",
  "NASA", "European Space Agency, ESA", "Scott Manley",
  "Fraser Cain", "Dr. Becky", "Cool Worlds", "Launch Pad Astronomy",
  "Proko", "Draw with Jazza", "The Art Assignment", "Blender Guru", "Ctrl+Paint",
  "Adam Neely", "12tone", "Rick Beato", "David Bennett Piano",
  "8-bit Music Theory", "Signals Music Studio",
  "Dr. Najeeb Lectures", "Lecturio Medical", "OnlineMedEd",
  "Physeo", "Dirty Medicine", "Med School Insiders"
];
